version: 2.1

orbs:
  android: circleci/android@2.3.0

commands:
  change-java-version:
    description: |
      Change default java version from OpenJDK v17.
    parameters:
      java-version:
        default: 17
        description: |
          The version of OpenJDK to change to
        type: integer
    steps:
      - run:
          command: |-
            #!/bin/bash
             CURRENT_JAVA_VER="$( java -version 2>&1 | head -1 | cut -d'"' -f2 | sed '/^1\./s///' | cut -d'.' -f1 )"
                    CURRENT_JAVAC_VER="$( javac -version 2>&1 | head -1 | cut -f 2- -d ' ' | sed '/^1\./s///' | cut -d'.' -f1 )"
                    echo "Current Java Version: $CURRENT_JAVA_VER"
                    echo "Current Java Compiler Version : $CURRENT_JAVAC_VER"
                    sudo apt install openjdk-"${PARAM_JAVA_VER}"-jdk
                    sudo update-alternatives --set javac /usr/lib/jvm/java-"${PARAM_JAVA_VER}"-openjdk-amd64/bin/javac
                    sudo update-alternatives --set java /usr/lib/jvm/java-"${PARAM_JAVA_VER}"-openjdk-amd64/bin/java
                    NEW_JAVA_VER="$( java -version 2>&1 | head -1 | cut -d'"' -f2 | sed '/^1\./s///' | cut -d'.' -f1 )"
                    NEW_JAVAC_VER="$( javac -version 2>&1 | head -1 | cut -f 2- -d ' ' | sed '/^1\./s///' | cut -d'.' -f1 )"
                    echo "New Java Version : $NEW_JAVA_VER"
                    echo "New Java Compiler Version : $NEW_JAVAC_VER"
          environment:
            PARAM_JAVA_VER: << parameters.java-version >>
          name: Change OpenJDK version to << parameters.java-version >>

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - run:
          name: Download Dependencies
          command: java --version

workflows:
  build:
    jobs:
      - build
